[project]
name = "note-manager-mcp-server"
version = "0.1.0"
description = "An MCP Server for Note management"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.7.1",
]
